name: Machine-Learning-Client

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install gcc
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake  gcc  ffmpeg libsm6 libxext6 libgl1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipenv
        pipenv sync --dev --python $(which python)
        pipenv shell --fancy --python $(which python)

    - name: Test with pytest (machine-learning-client)
      run: |
        cd machine-learning-client
        pipenv run coverage run -m pytest
        pipenv run coverage report --fail-under=80
